version: '3'
services:
  exrate:
    container_name: "exrate"
    image: "exrate"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      GA_PROPERTY_ID: UA-239926907-1
      GA_RATE_METRIC: cr1
